var roots = {
	"acet": { "definition": "sour, vinegar", "words": {} },
	"acr": { "definition": "height, summit, tip", "words": {} },
	"acu": { "definition": "sharp", "words": {} },
	"adip": { "definition": "fat", "words": {} },
	"aero": { "definition": "air", "words": {} },
	"aesth": { "definition": "feeling, sensation", "words": {} },
	"aev": { "definition": "age", "words": {} },
	"ag": { "definition": "do, go, move", "words": {} },
	"agogue": { "definition": "lead", "words": {} },
	"agro": { "definition": "field", "words": {} },
	"alac": { "definition": "cheerful", "words": {} },
	"alb": { "definition": "dull white", "words": {} },
	"alg": { "definition": "pain", "words": {} },
	"all": { "definition": "other", "words": {} },
	"alt": { "definition": "high, deep", "words": {} },
	"ambi": { "definition": "both", "words": {} },
	"ambul": { "definition": "to walk", "words": {} },
	"ampl": { "definition": "ample, abundant, bountiful, large", "words": {} },
	"anem": { "definition": "wind", "words": {} },
	"anim": { "definition": "breath, life, spirit", "words": {} },
	"anth": { "definition": "flower", "words": {} },
	"anthrac": { "definition": "coal", "words": {} },
	"anthrop": { "definition": "human", "words": {} },
	"anti": { "definition": "against; preventing", "words": {} },
	"aper": { "definition": "open", "words": {} },
	"aqua": { "definition": "water", "words": {} },
	"ara": { "definition": "plow, till", "words": {} },
	"arbit": { "definition": "judge", "words": {} },
	"arcan": { "definition": "box", "words": {} },
	"arct": { "definition": "of or near the North Pole; relating to cold", "words": {} },
	"ard": { "definition": "heat, glow, passion", "words": {} },
	"ardu": { "definition": "difficult", "words": {} },
	"aret": { "definition": "virtue", "words": {} },
	"argent": { "definition": "silver", "words": {} },
	"arid": { "definition": "be dry", "words": {} },
	"arist": { "definition": "excellence", "words": {} },
	"art": { "definition": "art, skill", "words": {} },
	"arthr": { "definition": "jointed", "words": {} },
	"asin": { "definition": "ass", "words": {} },
	"asper": { "definition": "rough", "words": {} },
	"athl": { "definition": "prize", "words": {} },
	"athroid": { "definition": "gathered or lumped together", "words": {} },
	"audac": { "definition": "daring", "words": {} },
	"aur": { "definition": "relating to gold, or gold-colored", "words": {} },
	"av": { "definition": "desire", "words": {} },
	"axi": { "definition": "axis", "words": {} },
	"axon": { "definition": "axis, axle", "words": {} },
	"bac": { "definition": "rod-shaped", "words": {} },
	"bar": { "definition": "weight pressure", "words": {} },
	"ben": { "definition": "good, well", "words": {} },
	"bi": { "definition": "two", "words": {} },
	"bib": { "definition": "drink", "words": {} },
	"bibl": { "definition": "book", "words": {} },
	"bio": { "definition": "life", "words": {} },
	"blast": { "definition": "germ embryo, bud, cell with nucleus", "words": {} },
	"blenn": { "definition": "slime", "words": {} },
	"bon": { "definition": "good", "words": {} },
	"bore": { "definition": "north", "words": {} },
	"botan": { "definition": "plant", "words": {} },
	"brachio": { "definition": "arm", "words": {} },
	"brachy": { "definition": "short", "words": {} },
	"branchi": { "definition": "gill", "words": {} },
	"brev": { "definition": "brief, short (time)", "words": {} },
	"brom": { "definition": "stench", "words": {} },
	"bronch": { "definition": "windpipe", "words": {} },
	"bronto": { "definition": "thunder", "words": {} },
	"bucc": { "definition": "cheek, mouth cavity", "words": {} },
	"bulb": { "definition": "bulbous", "words": {} },
	"bull": { "definition": "bubble, flask", "words": {} },
	"burs": { "definition": "pouch, purse", "words": {} },
	"cac": { "definition": "bad", "words": {} },
	"cal": { "definition": "heat", "words": {} },
	"calc": { "definition": "stone", "words": {} },
	"calyp": { "definition": "cover", "words": {} },
	"camer": { "definition": "vault", "words": {} },
	"camis": { "definition": "shirt", "words": {} },
	"camp": { "definition": "field", "words": {} },
	"can": { "definition": "reed, rod", "words": {} },
	"capr": { "definition": "goat", "words": {} },
	"caps": { "definition": "box, case", "words": {} },
	"carbon": { "definition": "coal", "words": {} },
	"carcer": { "definition": "jail", "words": {} },
	"carcin": { "definition": "cancer (disease)", "words": {} },
	"cardi": { "definition": "heart", "words": {} },
	"cardin": { "definition": "hinge", "words": {} },
	"carn": { "definition": "flesh", "words": {} },
	"carp": { "definition": "wrist", "words": {} },
	"cast": { "definition": "pure, cut", "words": {} },
	"caten": { "definition": "chain", "words": {} },
	"cathar": { "definition": "pure", "words": {} },
	"caud": { "definition": "tail", "words": {} },
	"cav": { "definition": "hollow", "words": {} },
	"cel": { "definition": "hide", "words": {} },
	"celer": { "definition": "quick", "words": {} },
	"cen": { "definition": "empty", "words": {} },
	"cens": { "definition": "to assess", "words": {} },
	"cent": { "definition": "hundred", "words": {} },
	"centen": { "definition": "hundred each", "words": {} },
	"centesim": { "definition": "hundredth", "words": {} },
	"cephal": { "definition": "head", "words": {} },
	"cerat": { "definition": "horn", "words": {} },
	"cervic": { "definition": "relating to the neck, relating to the cervix", "words": {} },
	"ceter": { "definition": "other", "words": {} },
	"chelon": { "definition": "relating to a turtle", "words": {} },
	"chir": { "definition": "hand", "words": {} },
	"chlor": { "definition": "green", "words": {} },
	"chord": { "definition": "cord", "words": {} },
	"chore": { "definition": "relating to dance", "words": {} },
	"chrom": { "definition": "color", "words": {} },
	"chron": { "definition": "time", "words": {} },
	"chrys": { "definition": "gold", "words": {} },
	"cide": { "definition": "act of killing; killer", "words": {} },
	"cili": { "definition": "eyelash", "words": {} },
	"ciner": { "definition": "ash", "words": {} },
	"circ": { "definition": "circle, ring", "words": {} },
	"circum": { "definition": "around", "words": {} },
	"cirr": { "definition": "curl, tentacle", "words": {} },
	"cit": { "definition": "call, start", "words": {} },
	"civ": { "definition": "citizen", "words": {} },
	"clad": { "definition": "branch", "words": {} },
	"clam": { "definition": "cry out", "words": {} },
	"clar": { "definition": "clear", "words": {} },
	"clast": { "definition": "broken", "words": {} },
	"claus": { "definition": "shut; closed", "words": {} },
	"clav": { "definition": "key", "words": {} },
	"cleist": { "definition": "closed", "words": {} },
	"cleithr": { "definition": "bar, key", "words": {} },
	"clement": { "definition": "mild", "words": {} },
	"clin": { "definition": "lean, recline", "words": {} },
	"cochl": { "definition": "snail, spiral shell", "words": {} },
	"coel": { "definition": "hollow", "words": {} },
	"col": { "definition": "strain", "words": {} },
	"coll": { "definition": "neck", "words": {} },
	"color": { "definition": "color", "words": {} },
	"comi": { "definition": "friendly, kind", "words": {} },
	"con": { "definition": "with)  (together", "words": {} },
	"condi": { "definition": "season", "words": {} },
	"contra": { "definition": "against", "words": {} },
	"copi": { "definition": "plenty", "words": {} },
	"copr": { "definition": "dung", "words": {} },
	"copul": { "definition": "bond", "words": {} },
	"corac": { "definition": "raven", "words": {} },
	"cori": { "definition": "hide, leather", "words": {} },
	"corn": { "definition": "horn", "words": {} },
	"coron": { "definition": "crown", "words": {} },
	"cortic": { "definition": "bark", "words": {} },
	"cosm": { "definition": "universe", "words": {} },
	"cosmet": { "definition": "the art of dress and ornament", "words": {} },
	"cost": { "definition": "rib", "words": {} },
	"cotyl": { "definition": "cup", "words": {} },
	"cracy": { "definition": "government, rule, authority", "words": {} },
	"crani": { "definition": "skull", "words": {} },
	"crass": { "definition": "thick", "words": {} },
	"crea": { "definition": "make", "words": {} },
	"cred": { "definition": "believe, trust", "words": {} },
	"crep": { "definition": "boot shoe", "words": {} },
	"cresc": { "definition": "grow, rise", "words": {} },
	"cribr": { "definition": "sieve", "words": {} },
	"cric": { "definition": "ring", "words": {} },
	"crisp": { "definition": "curled", "words": {} },
	"crist": { "definition": "crest", "words": {} },
	"cross": { "definition": "fringe tassel", "words": {} },
	"cruc": { "definition": "cross", "words": {} },
	"crur": { "definition": "leg, shank", "words": {} },
	"crypt": { "definition": "hidden; vault", "words": {} },
	"cten": { "definition": "comb", "words": {} },
	"cub": { "definition": "lie", "words": {} },
	"culin": { "definition": "kitchen", "words": {} },
	"culp": { "definition": "blame, fault", "words": {} },
	"cune": { "definition": "wedge", "words": {} },
	"cur": { "definition": "care for", "words": {} },
	"curv": { "definition": "bent", "words": {} },
	"cuspid": { "definition": "lance point", "words": {} },
	"cut": { "definition": "skin", "words": {} },
	"cyan": { "definition": "blue", "words": {} },
	"cycl": { "definition": "circular", "words": {} },
	"cylind": { "definition": "roll", "words": {} },
	"cyn": { "definition": "dog", "words": {} },
	"cyst": { "definition": "capsule", "words": {} },
	"cyt": { "definition": "cell", "words": {} },
	"dactyl": { "definition": "finger; toe", "words": {} },
	"daman": { "definition": "to tame", "words": {} },
	"de": { "definition": "down, away from, removing", "words": {} },
	"dec": { "definition": "ten", "words": {} },
	"decim": { "definition": "tenth part", "words": {} },
	"decor": { "definition": "ornament", "words": {} },
	"del": { "definition": "delete", "words": {} },
	"dem": { "definition": "people", "words": {} },
	"den": { "definition": "ten each", "words": {} },
	"dendr": { "definition": "resembling a tree", "words": {} },
	"dens": { "definition": "thick", "words": {} },
	"dent": { "definition": "tooth", "words": {} },
	"der": { "definition": "skin", "words": {} },
	"derm": { "definition": "skin", "words": {} },
	"deuter": { "definition": "second", "words": {} },
	"dexi": { "definition": "right", "words": {} },
	"dexter": { "definition": "right", "words": {} },
	"di": { "definition": "two", "words": {} },
	"dia": { "definition": "apart, through", "words": {} },
	"dida": { "definition": "teach", "words": {} },
	"digit": { "definition": "finger", "words": {} },
	"dino": { "definition": "terrifying", "words": {} },
	"dipl": { "definition": "double; twofold", "words": {} },
	"dodec": { "definition": "twelve", "words": {} },
	"dol": { "definition": "pain", "words": {} },
	"dom": { "definition": "house", "words": {} },
	"domin": { "definition": "master", "words": {} },
	"domit": { "definition": "tame", "words": {} },
	"don": { "definition": "give", "words": {} },
	"dorm": { "definition": "sleep", "words": {} },
	"dors": { "definition": "back", "words": {} },
	"drom": { "definition": "run", "words": {} },
	"du": { "definition": "two", "words": {} },
	"dub": { "definition": "doubtful", "words": {} },
	"dulc": { "definition": "sweet", "words": {} },
	"dur": { "definition": "hard", "words": {} },
	"dy": { "definition": "two", "words": {} },
	"dyna": { "definition": "power; motion; energy", "words": {} },
	"dys": { "definition": "ill; bad", "words": {} },
	"ec": { "definition": "out", "words": {} },
	"ecclesi": { "definition": "assembly, congregation", "words": {} },
	"eco": { "definition": "house", "words": {} },
	"ecto": { "definition": "outside", "words": {} },
	"eg": { "definition": "goat", "words": {} },
	"eiren": { "definition": "peace", "words": {} },
	"electr": { "definition": "amber", "words": {} },
	"eme": { "definition": "vomit", "words": {} },
	"emul": { "definition": "striving to equal, rivaling", "words": {} },
	"en": { "definition": "in; with", "words": {} },
	"encephal": { "definition": "brain", "words": {} },
	"endo": { "definition": "inside, within", "words": {} },
	"engy": { "definition": "narrow", "words": {} },
	"ennea": { "definition": "nine", "words": {} },
	"ens": { "definition": "sword", "words": {} },
	"entero": { "definition": "intestine", "words": {} },
	"epi": { "definition": "upon", "words": {} },
	"equ": { "definition": "horse", "words": {} },
	"erg": { "definition": "work", "words": {} },
	"erot": { "definition": "(sexual) love", "words": {} },
	"err": { "definition": "stray", "words": {} },
	"erythr": { "definition": "red", "words": {} },
	"eso": { "definition": "within", "words": {} },
	"eth": { "definition": "custom, habit", "words": {} },
	"ethm": { "definition": "sieve, sift", "words": {} },
	"ethn": { "definition": "people, race, tribe, nation", "words": {} },
	"etym": { "definition": "true", "words": {} },
	"eu": { "definition": "well, good", "words": {} },
	"eur": { "definition": "wide", "words": {} },
	"ex": { "definition": "out; from", "words": {} },
	"exo": { "definition": "outside", "words": {} },
	"extrem": { "definition": "outermost, utmost", "words": {} },
	"fab": { "definition": "bean", "words": {} },
	"falc": { "definition": "sickle", "words": {} },
	"famili": { "definition": "a close attendant", "words": {} },
	"fasc": { "definition": "bundle", "words": {} },
	"fatu": { "definition": "foolish, useless", "words": {} },
	"feder": { "definition": "treaty, agreement, contract, league, pact", "words": {} },
	"fel": { "definition": "cat", "words": {} },
	"felic": { "definition": "happy, merry", "words": {} },
	"fell": { "definition": "suck", "words": {} },
	"femin": { "definition": "women, female", "words": {} },
	"femor": { "definition": "thigh", "words": {} },
	"fenestr": { "definition": "window", "words": {} },
	"fer": { "definition": "to bear, carry", "words": {} },
	"feroc": { "definition": "fierce", "words": {} },
	"ferr": { "definition": "iron", "words": {} },
	"ferv": { "definition": "boil, glow", "words": {} },
	"fet": { "definition": "stink", "words": {} },
	"fic": { "definition": "fig", "words": {} },
	"fil": { "definition": "thread", "words": {} },
	"fili": { "definition": "son", "words": {} },
	"fin": { "definition": "end", "words": {} },
	"firm": { "definition": "firm, strong", "words": {} },
	"fistul": { "definition": "hollow, tube", "words": {} },
	"fix": { "definition": "attach", "words": {} },
	"fl": { "definition": "blow", "words": {} },
	"flacc": { "definition": "flabby", "words": {} },
	"flav": { "definition": "yellow", "words": {} },
	"flor": { "definition": "flower", "words": {} },
	"foc": { "definition": "hearth", "words": {} },
	"foen": { "definition": "hay", "words": {} },
	"foli": { "definition": "leaf", "words": {} },
	"font": { "definition": "spring", "words": {} },
	"for": { "definition": "bore, drill", "words": {} },
	"form": { "definition": "ant", "words": {} },
	"fornic": { "definition": "vault", "words": {} },
	"fort": { "definition": "strong", "words": {} },
	"fove": { "definition": "shallow round depression", "words": {} },
	"frater": { "definition": "brother", "words": {} },
	"frig": { "definition": "cold", "words": {} },
	"front": { "definition": "forehead", "words": {} },
	"fulm": { "definition": "flash", "words": {} },
	"fum": { "definition": "smoke", "words": {} },
	"funct": { "definition": "do", "words": {} },
	"fund": { "definition": "bottom", "words": {} },
	"furc": { "definition": "fork", "words": {} },
	"fusc": { "definition": "dark", "words": {} },
	"gam": { "definition": "marriage, wedding", "words": {} },
	"gamb": { "definition": "leg", "words": {} },
	"gamy": { "definition": "marriage", "words": {} },
	"gastr": { "definition": "stomach", "words": {} },
	"geiton": { "definition": "neighbor", "words": {} },
	"gel": { "definition": "icy cold", "words": {} },
	"geno": { "definition": "culture; race", "words": {} },
	"ger": { "definition": "old", "words": {} },
	"germ": { "definition": "sprout", "words": {} },
	"glabr": { "definition": "hairless", "words": {} },
	"glaci": { "definition": "ice", "words": {} },
	"gladi": { "definition": "sword", "words": {} },
	"glia": { "definition": "glue", "words": {} },
	"glob": { "definition": "sphere", "words": {} },
	"glori": { "definition": "glory", "words": {} },
	"glutin": { "definition": "glue", "words": {} },
	"glyc": { "definition": "sweet", "words": {} },
	"glyph": { "definition": "carve", "words": {} },
	"gnath": { "definition": "jaw", "words": {} },
	"gon": { "definition": "angle", "words": {} },
	"gramm": { "definition": "letter, writing", "words": {} },
	"gran": { "definition": "grain", "words": {} },
	"grand": { "definition": "grand", "words": {} },
	"graph": { "definition": "draw; write", "words": {} },
	"grat": { "definition": "thank, please", "words": {} },
	"grav": { "definition": "heavy", "words": {} },
	"greg": { "definition": "flock, herd", "words": {} },
	"gubern": { "definition": "govern, pilot", "words": {} },
	"gust": { "definition": "taste", "words": {} },
	"gutt": { "definition": "drop", "words": {} },
	"guttur": { "definition": "throat", "words": {} },
	"gymn": { "definition": "nude", "words": {} },
	"hadr": { "definition": "thick", "words": {} },
	"hal": { "definition": "to breath", "words": {} },
	"hapl": { "definition": "simple, single", "words": {} },
	"hedo": { "definition": "pleasure", "words": {} },
	"hedron": { "definition": "face", "words": {} },
	"heli": { "definition": "sun", "words": {} },
	"helico": { "definition": "spiral", "words": {} },
	"hemer": { "definition": "day", "words": {} },
	"hemi": { "definition": "half", "words": {} },
	"hen": { "definition": "one", "words": {} },
	"hendec": { "definition": "eleven", "words": {} },
	"hept": { "definition": "seven", "words": {} },
	"herald": { "definition": "messenger, envoy", "words": {} },
	"herb": { "definition": "grass", "words": {} },
	"herp": { "definition": "creep", "words": {} },
	"heter": { "definition": "different, other", "words": {} },
	"heur": { "definition": "find", "words": {} },
	"hex": { "definition": "six", "words": {} },
	"hibern": { "definition": "wintry", "words": {} },
	"hiem": { "definition": "winter", "words": {} },
	"hier": { "definition": "sacred", "words": {} },
	"hipp": { "definition": "horse", "words": {} },
	"hirsut": { "definition": "hairy", "words": {} },
	"hispid": { "definition": "bristly", "words": {} },
	"histri": { "definition": "actor", "words": {} },
	"hod": { "definition": "way", "words": {} },
	"hol": { "definition": "whole", "words": {} },
	"hom": { "definition": "same", "words": {} },
	"homal": { "definition": "even, flat", "words": {} },
	"home": { "definition": "like", "words": {} },
	"homin": { "definition": "human", "words": {} },
	"honor": { "definition": "esteem", "words": {} },
	"hor": { "definition": "hour", "words": {} },
	"horm": { "definition": "that which excites", "words": {} },
	"hort": { "definition": "garden", "words": {} },
	"hospit": { "definition": "host", "words": {} },
	"host": { "definition": "enemy", "words": {} },
	"hum": { "definition": "ground", "words": {} },
	"hyal": { "definition": "glass", "words": {} },
	"hydr": { "definition": "water", "words": {} },
	"hydrochloric": { "definition": "green acid water", "words": {} },
	"hygr": { "definition": "wet", "words": {} },
	"hymen": { "definition": "skin or membrane", "words": {} },
	"hyo": { "definition": "U-shaped", "words": {} },
	"hyp": { "definition": "under", "words": {} },
	"hyper": { "definition": "above, over", "words": {} },
	"hypn": { "definition": "sleep", "words": {} },
	"hyster": { "definition": "later", "words": {} },
	"iatr": { "definition": "heal", "words": {} },
	"iatry": { "definition": "healing", "words": {} },
	"ichthy": { "definition": "fish", "words": {} },
	"icos": { "definition": "twenty", "words": {} },
	"id": { "definition": "shape", "words": {} },
	"ide": { "definition": "idea; thought", "words": {} },
	"idi": { "definition": "own, peculiarity", "words": {} },
	"ign": { "definition": "fire", "words": {} },
	"imagin": { "definition": "copy", "words": {} },
	"inan": { "definition": "empty, vain", "words": {} },
	"infra": { "definition": "below, under", "words": {} },
	"insul": { "definition": "island", "words": {} },
	"inter": { "definition": "among, between", "words": {} },
	"intra": { "definition": "within", "words": {} },
	"irid": { "definition": "rainbow", "words": {} },
	"ischi": { "definition": "hip joint", "words": {} },
	"iter": { "definition": "again", "words": {} },
	"itiner": { "definition": "journey", "words": {} },
	"itis": { "definition": "inflammation", "words": {} },
	"jac": { "definition": "lie", "words": {} },
	"janu": { "definition": "door", "words": {} },
	"joc": { "definition": "joke", "words": {} },
	"judic": { "definition": "judge", "words": {} },
	"jug": { "definition": "yoke", "words": {} },
	"junior": { "definition": "younger", "words": {} },
	"juven": { "definition": "young, youth", "words": {} },
	"juxta": { "definition": "beside, near", "words": {} },
	"klept": { "definition": "steal", "words": {} },
	"kudo": { "definition": "glory", "words": {} },
	"labi": { "definition": "lip", "words": {} },
	"labor": { "definition": "work", "words": {} },
	"lacer": { "definition": "tear", "words": {} },
	"lacrim": { "definition": "cry, tears", "words": {} },
	"lact": { "definition": "milk", "words": {} },
	"lamin": { "definition": "layer, slice", "words": {} },
	"lamp": { "definition": "torch", "words": {} },
	"lapid": { "definition": "stone", "words": {} },
	"larg": { "definition": "large", "words": {} },
	"larv": { "definition": "ghost, mask", "words": {} },
	"lat": { "definition": "broad, wide", "words": {} },
	"later": { "definition": "side", "words": {} },
	"lav": { "definition": "wash", "words": {} },
	"lax": { "definition": "not tense", "words": {} },
	"lecith": { "definition": "egg yolk", "words": {} },
	"leg": { "definition": "send", "words": {} },
	"lei": { "definition": "smooth", "words": {} },
	"lekan": { "definition": "dish, pot", "words": {} },
	"leni": { "definition": "gentle", "words": {} },
	"leon": { "definition": "lion", "words": {} },
	"lep": { "definition": "flake, scale", "words": {} },
	"lepsi": { "definition": "grasp, seize", "words": {} },
	"lev": { "definition": "lift, light, raise", "words": {} },
	"libr": { "definition": "book", "words": {} },
	"lig": { "definition": "bind", "words": {} },
	"limac": { "definition": "slug", "words": {} },
	"limpa": { "definition": "clear, water", "words": {} },
	"line": { "definition": "smear, smudge", "words": {} },
	"lingu": { "definition": "language, tongue", "words": {} },
	"lip": { "definition": "fat", "words": {} },
	"liq": { "definition": "flow", "words": {} },
	"lit": { "definition": "prayer, supplication", "words": {} },
	"liter": { "definition": "letter", "words": {} },
	"lith": { "definition": "stone", "words": {} },
	"loc": { "definition": "place", "words": {} },
	"logy": { "definition": "any branch of science", "words": {} },
	"long": { "definition": "long", "words": {} },
	"luc": { "definition": "bright, light", "words": {} },
	"lumin": { "definition": "light", "words": {} },
	"lun": { "definition": "moon", "words": {} },
	"luteo": { "definition": "yellow, golden", "words": {} },
	"macer": { "definition": "lean", "words": {} },
	"macro": { "definition": "long", "words": {} },
	"magn": { "definition": "great, large", "words": {} },
	"maj": { "definition": "greater", "words": {} },
	"mal": { "definition": "bad, wretched", "words": {} },
	"mamm": { "definition": "breast", "words": {} },
	"man": { "definition": "flow", "words": {} },
	"mancy": { "definition": "divination", "words": {} },
	"mar": { "definition": "sea", "words": {} },
	"mascul": { "definition": "male, man", "words": {} },
	"maxim": { "definition": "greatest", "words": {} },
	"mechan": { "definition": "machine or instrument", "words": {} },
	"medi": { "definition": "middle", "words": {} },
	"mei": { "definition": "less", "words": {} },
	"melan": { "definition": "black, dark", "words": {} },
	"melior": { "definition": "better", "words": {} },
	"mell": { "definition": "honey", "words": {} },
	"memor": { "definition": "remember", "words": {} },
	"men": { "definition": "month", "words": {} },
	"mend": { "definition": "defect, fault", "words": {} },
	"mening": { "definition": "membrane", "words": {} },
	"menstru": { "definition": "monthly", "words": {} },
	"mensur": { "definition": "measure", "words": {} },
	"ment": { "definition": "mind", "words": {} },
	"mer": { "definition": "part", "words": {} },
	"merc": { "definition": "reward, wages, hire", "words": {} },
	"merg": { "definition": "plunge", "words": {} },
	"mes": { "definition": "middle", "words": {} },
	"meta": { "definition": "change; alteration", "words": {} },
	"meter": { "definition": "measure", "words": {} },
	"metr": { "definition": "mother", "words": {} },
	"mic": { "definition": "grain", "words": {} },
	"micro": { "definition": "small", "words": {} },
	"migr": { "definition": "wander", "words": {} },
	"milit": { "definition": "soldier", "words": {} },
	"mill": { "definition": "thousand", "words": {} },
	"millen": { "definition": "thousand each", "words": {} },
	"mim": { "definition": "repeat", "words": {} },
	"min": { "definition": "less, smaller", "words": {} },
	"mina": { "definition": "lead", "words": {} },
	"mir": { "definition": "wonder, amazement", "words": {} },
	"mis": { "definition": "hate", "words": {} },
	"miser": { "definition": "unhappy, wretched", "words": {} },
	"mit": { "definition": "thread", "words": {} },
	"mne": { "definition": "memory", "words": {} },
	"mol": { "definition": "grind", "words": {} },
	"moll": { "definition": "soft", "words": {} },
	"mon": { "definition": "one", "words": {} },
	"monil": { "definition": "string of beads", "words": {} },
	"monstra": { "definition": "show", "words": {} },
	"mont": { "definition": "mountain", "words": {} },
	"mor": { "definition": "disposition", "words": {} },
	"mora": { "definition": "pause, delay", "words": {} },
	"mord": { "definition": "bite", "words": {} },
	"morph": { "definition": "shape", "words": {} },
	"mort": { "definition": "death", "words": {} },
	"multi": { "definition": "many, much", "words": {} },
	"mund": { "definition": "world", "words": {} },
	"mur": { "definition": "wall", "words": {} },
	"mus": { "definition": "thief", "words": {} },
	"musc": { "definition": "fly", "words": {} },
	"mut": { "definition": "change", "words": {} },
	"my": { "definition": "shut (the eyes)", "words": {} },
	"myc": { "definition": "fungus", "words": {} },
	"myri": { "definition": "countless, ten thousand", "words": {} },
	"myth": { "definition": "story", "words": {} },
	"myx": { "definition": "slime", "words": {} },
	"myz": { "definition": "suck", "words": {} },
	"nar": { "definition": "nostril", "words": {} },
	"narc": { "definition": "numb", "words": {} },
	"narr": { "definition": "tell", "words": {} },
	"nas": { "definition": "nose", "words": {} },
	"naut": { "definition": "ship", "words": {} },
	"nav": { "definition": "ship", "words": {} },
	"necr": { "definition": "dead", "words": {} },
	"nect": { "definition": "swimming", "words": {} },
	"neg": { "definition": "say no", "words": {} },
	"nema": { "definition": "hair", "words": {} },
	"nemor": { "definition": "grove, woods", "words": {} },
	"nephr": { "definition": "kidney", "words": {} },
	"nerv": { "definition": "sinew, nerve", "words": {} },
	"nes": { "definition": "island", "words": {} },
	"neur": { "definition": "nerve", "words": {} },
	"nex": { "definition": "join; tie", "words": {} },
	"nict": { "definition": "beckon, wink", "words": {} },
	"nigr": { "definition": "black", "words": {} },
	"nihil": { "definition": "nothing", "words": {} },
	"noc": { "definition": "hurt, harm", "words": {} },
	"noct": { "definition": "night", "words": {} },
	"nod": { "definition": "knot", "words": {} },
	"nom": { "definition": "arrangement, law, order", "words": {} },
	"nomad": { "definition": "those who let pasture herds", "words": {} },
	"non": { "definition": "ninth", "words": {} },
	"nonagen": { "definition": "ninety each", "words": {} },
	"nonagesim": { "definition": "ninetieth", "words": {} },
	"not": { "definition": "letter, note, paper", "words": {} },
	"noth": { "definition": "spurious", "words": {} },
	"nov": { "definition": "new", "words": {} },
	"noven": { "definition": "nine each", "words": {} },
	"novendec": { "definition": "nineteen", "words": {} },
	"nu": { "definition": "nod", "words": {} },
	"nuc": { "definition": "nut", "words": {} },
	"nuch": { "definition": "back of neck", "words": {} },
	"nud": { "definition": "naked", "words": {} },
	"null": { "definition": "none", "words": {} },
	"numer": { "definition": "number", "words": {} },
	"nunci": { "definition": "announce", "words": {} },
	"nutri": { "definition": "nourish", "words": {} },
	"oct": { "definition": "eight", "words": {} },
	"octav": { "definition": "eighth", "words": {} },
	"octogen": { "definition": "eighty each", "words": {} },
	"octogesim": { "definition": "eightieth", "words": {} },
	"octon": { "definition": "eight each", "words": {} },
	"ocul": { "definition": "eye", "words": {} },
	"od": { "definition": "path, way", "words": {} },
	"odi": { "definition": "hate", "words": {} },
	"odont": { "definition": "tooth", "words": {} },
	"odor": { "definition": "fragrant", "words": {} },
	"odyn": { "definition": "pain", "words": {} },
	"oeco": { "definition": "house", "words": {} },
	"oed": { "definition": "swell, swollen", "words": {} },
	"oen": { "definition": "wine", "words": {} },
	"oesophag": { "definition": "gullet", "words": {} },
	"ogdo": { "definition": "eighth", "words": {} },
	"oid": { "definition": "like", "words": {} },
	"ole": { "definition": "oil", "words": {} },
	"olecran": { "definition": "skull of elbow", "words": {} },
	"olig": { "definition": "few", "words": {} },
	"oliv": { "definition": "olive", "words": {} },
	"om": { "definition": "shoulder", "words": {} },
	"oma": { "definition": "morbid growth, tumor", "words": {} },
	"omas": { "definition": "paunch", "words": {} },
	"oment": { "definition": "fat skin", "words": {} },
	"omin": { "definition": "creepy", "words": {} },
	"omm": { "definition": "eye", "words": {} },
	"omni": { "definition": "all", "words": {} },
	"omphal": { "definition": "navel", "words": {} },
	"oner": { "definition": "burden", "words": {} },
	"onom": { "definition": "name", "words": {} },
	"ont": { "definition": "existing", "words": {} },
	"onym": { "definition": "name", "words": {} },
	"oo": { "definition": "egg", "words": {} },
	"opac": { "definition": "shady", "words": {} },
	"oper": { "definition": "work", "words": {} },
	"opercul": { "definition": "little cover", "words": {} },
	"ophi": { "definition": "snake", "words": {} },
	"ophthalm": { "definition": "eye", "words": {} },
	"opisth": { "definition": "behind", "words": {} },
	"ops": { "definition": "face", "words": {} },
	"opt": { "definition": "choose", "words": {} },
	"optim": { "definition": "best", "words": {} },
	"or": { "definition": "mouth", "words": {} },
	"ora": { "definition": "pray, plead", "words": {} },
	"orb": { "definition": "circle", "words": {} },
	"orch": { "definition": "testicle", "words": {} },
	"ordin": { "definition": "order", "words": {} },
	"orex": { "definition": "longing, appetite", "words": {} },
	"organ": { "definition": "organ, instrument, tool", "words": {} },
	"orn": { "definition": "decorate", "words": {} },
	"ornith": { "definition": "bird", "words": {} },
	"orth": { "definition": "straight", "words": {} },
	"oscill": { "definition": "swing", "words": {} },
	"osis": { "definition": "state of being; abnormal condition; action", "words": {} },
	"oss": { "definition": "bone", "words": {} },
	"osteo": { "definition": "bone", "words": {} },
	"ostrac": { "definition": "shell", "words": {} },
	"ot": { "definition": "ear", "words": {} },
	"ov": { "definition": "egg", "words": {} },
	"over": { "definition": "close, cover", "words": {} },
	"ovi": { "definition": "sheep", "words": {} },
	"oxy": { "definition": "sharp, pointed", "words": {} },
	"pac": { "definition": "peace", "words": {} },
	"pach": { "definition": "thick", "words": {} },
	"pact": { "definition": "fasten", "words": {} },
	"paed": { "definition": "child", "words": {} },
	"pagin": { "definition": "page", "words": {} },
	"pal": { "definition": "stake", "words": {} },
	"palin": { "definition": "back", "words": {} },
	"pall": { "definition": "be pale", "words": {} },
	"palli": { "definition": "cloak", "words": {} },
	"palm": { "definition": "palm", "words": {} },
	"palp": { "definition": "touch", "words": {} },
	"palustr": { "definition": "in marshes", "words": {} },
	"par": { "definition": "order, prepare, provide, procure", "words": {} },
	"para": { "definition": "beside, near", "words": {} },
	"pariet": { "definition": "wall", "words": {} },
	"part": { "definition": "part", "words": {} },
	"parthen": { "definition": "maiden", "words": {} },
	"parv": { "definition": "little", "words": {} },
	"passer": { "definition": "sparrow", "words": {} },
	"pat": { "definition": "be open", "words": {} },
	"path": { "definition": "feeling, disease", "words": {} },
	"pauc": { "definition": "few", "words": {} },
	"pav": { "definition": "beat", "words": {} },
	"pecc": { "definition": "sin", "words": {} },
	"pect": { "definition": "fixed", "words": {} },
	"pector": { "definition": "chest", "words": {} },
	"pecu": { "definition": "property", "words": {} },
	"ped": { "definition": "foot", "words": {} },
	"pejor": { "definition": "worse", "words": {} },
	"pen": { "definition": "almost", "words": {} },
	"pent": { "definition": "five", "words": {} },
	"penta": { "definition": "five", "words": {} },
	"pentecost": { "definition": "fiftieth", "words": {} },
	"pept": { "definition": "digest", "words": {} },
	"per": { "definition": "thoroughly, through", "words": {} },
	"peran": { "definition": "across, beyond", "words": {} },
	"peri": { "definition": "around", "words": {} },
	"pessim": { "definition": "worst", "words": {} },
	"pet": { "definition": "strive toward", "words": {} },
	"petr": { "definition": "rock", "words": {} },
	"phae": { "definition": "dark", "words": {} },
	"phag": { "definition": "eat", "words": {} },
	"phalang": { "definition": "close formation of troops, finger bones", "words": {} },
	"phalar": { "definition": "having a patch of white", "words": {} },
	"pharmac": { "definition": "drug, medicine", "words": {} },
	"phleg": { "definition": "heat, inflammation", "words": {} },
	"phloe": { "definition": "tree bark", "words": {} },
	"phob": { "definition": "irrational fear", "words": {} },
	"phon": { "definition": "sound", "words": {} },
	"photo": { "definition": "light", "words": {} },
	"phragm": { "definition": "fence", "words": {} },
	"phren": { "definition": "diaphragm, mind", "words": {} },
	"phryn": { "definition": "toad, toad-like", "words": {} },
	"phyl": { "definition": "tribe", "words": {} },
	"phyll": { "definition": "leaf", "words": {} },
	"physalid": { "definition": "bladder", "words": {} },
	"physi": { "definition": "nature", "words": {} },
	"phyt": { "definition": "plant", "words": {} },
	"pi": { "definition": "kind, devout, pity", "words": {} },
	"pic": { "definition": "pitch", "words": {} },
	"pil": { "definition": "pillar, ball", "words": {} },
	"pin": { "definition": "pine", "words": {} },
	"pingu": { "definition": "fat", "words": {} },
	"pir": { "definition": "pear", "words": {} },
	"pisc": { "definition": "fish", "words": {} },
	"plac": { "definition": "calm", "words": {} },
	"plagi": { "definition": "oblique", "words": {} },
	"plan": { "definition": "flat", "words": {} },
	"plas": { "definition": "mould", "words": {} },
	"platy": { "definition": "flat, broad", "words": {} },
	"pleb": { "definition": "people", "words": {} },
	"plec": { "definition": "interwoven", "words": {} },
	"plen": { "definition": "full", "words": {} },
	"plesi": { "definition": "near", "words": {} },
	"pleth": { "definition": "full", "words": {} },
	"pleur": { "definition": "side", "words": {} },
	"plic": { "definition": "fold", "words": {} },
	"plinth": { "definition": "brick", "words": {} },
	"plor": { "definition": "", "words": {} },
	"plu": { "definition": "rain", "words": {} },
	"plum": { "definition": "feather", "words": {} },
	"plumb": { "definition": "lead", "words": {} },
	"plurim": { "definition": "most", "words": {} },
	"plut": { "definition": "wealth", "words": {} },
	"pneu": { "definition": "air, breath, lung", "words": {} },
	"pod": { "definition": "foot", "words": {} },
	"pogon": { "definition": "beard", "words": {} },
	"poie": { "definition": "make", "words": {} },
	"pol": { "definition": "pole", "words": {} },
	"polem": { "definition": "war", "words": {} },
	"poli": { "definition": "city", "words": {} },
	"polien": { "definition": "to sell", "words": {} },
	"pollic": { "definition": "thumb", "words": {} },
	"pollin": { "definition": "fine flour", "words": {} },
	"poly": { "definition": "many", "words": {} },
	"ponder": { "definition": "weight", "words": {} },
	"pont": { "definition": "bridge", "words": {} },
	"popul": { "definition": "people", "words": {} },
	"por": { "definition": "passage", "words": {} },
	"porc": { "definition": "pig", "words": {} },
	"porn": { "definition": "prostitute", "words": {} },
	"porphyr": { "definition": "purple", "words": {} },
	"port": { "definition": "carry", "words": {} },
	"post": { "definition": "after, behind", "words": {} },
	"pot": { "definition": "drink", "words": {} },
	"potam": { "definition": "river", "words": {} },
	"prasin": { "definition": "leek-green", "words": {} },
	"prav": { "definition": "crooked", "words": {} },
	"pre": { "definition": "before", "words": {} },
	"prec": { "definition": "pray", "words": {} },
	"pred": { "definition": "prey", "words": {} },
	"presby": { "definition": "old", "words": {} },
	"preter": { "definition": "past", "words": {} },
	"prim": { "definition": "first", "words": {} },
	"prior": { "definition": "former", "words": {} },
	"priv": { "definition": "separate", "words": {} },
	"pro": { "definition": "for, forward", "words": {} },
	"prob": { "definition": "worthy, good", "words": {} },
	"proct": { "definition": "anus", "words": {} },
	"prodig": { "definition": "prodigy", "words": {} },
	"propri": { "definition": "property; one's own", "words": {} },
	"pros": { "definition": "forward", "words": {} },
	"prot": { "definition": "first", "words": {} },
	"proxim": { "definition": "nearest", "words": {} },
	"prun": { "definition": "plum", "words": {} },
	"psamm": { "definition": "sand", "words": {} },
	"pseud": { "definition": "false", "words": {} },
	"psil": { "definition": "bare", "words": {} },
	"psych": { "definition": "mind", "words": {} },
	"psychr": { "definition": "cold", "words": {} },
	"pter": { "definition": "wing", "words": {} },
	"pto": { "definition": "fall", "words": {} },
	"pty": { "definition": "saliva", "words": {} },
	"ptych": { "definition": "fold, layer", "words": {} },
	"pub": { "definition": "sexually mature", "words": {} },
	"public": { "definition": "public", "words": {} },
	"pude": { "definition": "shame", "words": {} },
	"pulchr": { "definition": "beautiful", "words": {} },
	"pulmon": { "definition": "lung", "words": {} },
	"pulver": { "definition": "dust", "words": {} },
	"punct": { "definition": "point; dot", "words": {} },
	"pup": { "definition": "doll", "words": {} },
	"pur": { "definition": "pure", "words": {} },
	"purg": { "definition": "cleanse", "words": {} },
	"purpur": { "definition": "purple", "words": {} },
	"put": { "definition": "prune, reckon", "words": {} },
	"pyg": { "definition": "rump", "words": {} },
	"pyl": { "definition": "gate", "words": {} },
	"pyr": { "definition": "heat, fire", "words": {} },
	"quadr": { "definition": "four", "words": {} },
	"quadragen": { "definition": "forty each", "words": {} },
	"quadragesim": { "definition": "fortieth", "words": {} },
	"quart": { "definition": "fourth", "words": {} },
	"quasi": { "definition": "as if", "words": {} },
	"quatern": { "definition": "four each", "words": {} },
	"qui": { "definition": "rest", "words": {} },
	"quin": { "definition": "five each", "words": {} },
	"quindecim": { "definition": "fifteenth", "words": {} },
	"quinden": { "definition": "fifteen each", "words": {} },
	"quinque": { "definition": "five", "words": {} },
	"quint": { "definition": "fifth", "words": {} },
	"quot": { "definition": "how many, how great", "words": {} },
	"radi": { "definition": "beam, spoke", "words": {} },
	"radic": { "definition": "root", "words": {} },
	"ram": { "definition": "branch", "words": {} },
	"ran": { "definition": "frog", "words": {} },
	"ranc": { "definition": "rancidness, grudge, bitterness", "words": {} },
	"rap": { "definition": "turnip", "words": {} },
	"raph": { "definition": "seam", "words": {} },
	"rar": { "definition": "rare", "words": {} },
	"rauc": { "definition": "harsh, hoarse", "words": {} },
	"regul": { "definition": "rule", "words": {} },
	"rem": { "definition": "oar", "words": {} },
	"ren": { "definition": "kidney", "words": {} },
	"reneg": { "definition": "deny", "words": {} },
	"resid": { "definition": "left behind", "words": {} },
	"ret": { "definition": "net", "words": {} },
	"retro": { "definition": "backward, behind", "words": {} },
	"rex": { "definition": "king", "words": {} },
	"rhabd": { "definition": "rod", "words": {} },
	"rhag": { "definition": "rend, tear", "words": {} },
	"rhe": { "definition": "flow", "words": {} },
	"rhig": { "definition": "chill", "words": {} },
	"rhin": { "definition": "nose, snout", "words": {} },
	"rhiz": { "definition": "root", "words": {} },
	"rhod": { "definition": "rose", "words": {} },
	"rhomb": { "definition": "spinning top", "words": {} },
	"rhynch": { "definition": "snout", "words": {} },
	"robor": { "definition": "oak, strength", "words": {} },
	"rog": { "definition": "ask", "words": {} },
	"rostr": { "definition": "beak, prow", "words": {} },
	"rot": { "definition": "wheel", "words": {} },
	"rudi": { "definition": "unskilled, rough, unlearned", "words": {} },
	"rug": { "definition": "wrinkle", "words": {} },
	"rumin": { "definition": "throat", "words": {} },
	"rur": { "definition": "country", "words": {} },
	"sacchar": { "definition": "sugar", "words": {} },
	"sagac": { "definition": "wise", "words": {} },
	"sagitt": { "definition": "arrow", "words": {} },
	"sal": { "definition": "salt", "words": {} },
	"salic": { "definition": "willow", "words": {} },
	"salu": { "definition": "health, welfare", "words": {} },
	"salv": { "definition": "save", "words": {} },
	"san": { "definition": "healthy", "words": {} },
	"sanc": { "definition": "holy", "words": {} },
	"sanguin": { "definition": "blood", "words": {} },
	"sapon": { "definition": "soap", "words": {} },
	"sarc": { "definition": "tailor", "words": {} },
	"sati": { "definition": "enough", "words": {} },
	"saur": { "definition": "lizard, reptile", "words": {} },
	"saurus": { "definition": "lizard", "words": {} },
	"sax": { "definition": "rock", "words": {} },
	"scab": { "definition": "scratch", "words": {} },
	"scal": { "definition": "ladder, stairs", "words": {} },
	"scalen": { "definition": "uneven", "words": {} },
	"scaph": { "definition": "anything hollow, bowl, ship", "words": {} },
	"scel": { "definition": "leg, thigh", "words": {} },
	"schem": { "definition": "plan", "words": {} },
	"schis": { "definition": "split, cleft", "words": {} },
	"sci": { "definition": "know", "words": {} },
	"scler": { "definition": "hard", "words": {} },
	"scoli": { "definition": "crooked", "words": {} },
	"scrupl": { "definition": "uneasiness", "words": {} },
	"sculp": { "definition": "carve", "words": {} },
	"scut": { "definition": "shield", "words": {} },
	"scyph": { "definition": "cup", "words": {} },
	"seb": { "definition": "tallow", "words": {} },
	"sed": { "definition": "settle, calm", "words": {} },
	"sedec": { "definition": "sixteen", "words": {} },
	"sei": { "definition": "shake", "words": {} },
	"selen": { "definition": "moon", "words": {} },
	"sell": { "definition": "saddle, seat", "words": {} },
	"sema": { "definition": "sign", "words": {} },
	"semi": { "definition": "half", "words": {} },
	"semin": { "definition": "seed", "words": {} },
	"sen": { "definition": "six each", "words": {} },
	"sept": { "definition": "seven", "words": {} },
	"septen": { "definition": "seven each", "words": {} },
	"septim": { "definition": "seventh", "words": {} },
	"septuagen": { "definition": "seventy each", "words": {} },
	"septuagesim": { "definition": "seventieth", "words": {} },
	"septuagint": { "definition": "seventy", "words": {} },
	"ser": { "definition": "late", "words": {} },
	"serp": { "definition": "crawl, creep", "words": {} },
	"serr": { "definition": "saw, saw-toothed", "words": {} },
	"serv": { "definition": "save, protect, serve", "words": {} },
	"sesqui": { "definition": "one and a half", "words": {} },
	"set": { "definition": "bristle, hair", "words": {} },
	"sever": { "definition": "stern, strict, serious", "words": {} },
	"sexagen": { "definition": "sixty each", "words": {} },
	"sexagesim": { "definition": "sixtieth", "words": {} },
	"sext": { "definition": "sixth", "words": {} },
	"sibil": { "definition": "hiss", "words": {} },
	"sicc": { "definition": "dry", "words": {} },
	"sider": { "definition": "star", "words": {} },
	"sign": { "definition": "sign", "words": {} },
	"sil": { "definition": "quiet or still", "words": {} },
	"silv": { "definition": "forest", "words": {} },
	"simi": { "definition": "ape, monkey", "words": {} },
	"singul": { "definition": "one each", "words": {} },
	"sinistr": { "definition": "left", "words": {} },
	"sinu": { "definition": "(to draw) a line", "words": {} },
	"sinus": { "definition": "hollow", "words": {} },
	"siph": { "definition": "tube", "words": {} },
	"sist": { "definition": "cause to stand", "words": {} },
	"sit": { "definition": "food, grain, wheat", "words": {} },
	"soci": { "definition": "group", "words": {} },
	"sol": { "definition": "alone, only", "words": {} },
	"sole": { "definition": "accustomed", "words": {} },
	"solen": { "definition": "pipe, channel", "words": {} },
	"soma": { "definition": "body", "words": {} },
	"somn": { "definition": "sleep", "words": {} },
	"somni": { "definition": "dream", "words": {} },
	"son": { "definition": "sound", "words": {} },
	"soph": { "definition": "wise", "words": {} },
	"sopor": { "definition": "deep sleep", "words": {} },
	"sord": { "definition": "dirt", "words": {} },
	"soror": { "definition": "sister", "words": {} },
	"spati": { "definition": "space", "words": {} },
	"sper": { "definition": "hope", "words": {} },
	"sphen": { "definition": "wedge", "words": {} },
	"spher": { "definition": "ball", "words": {} },
	"spic": { "definition": "spike", "words": {} },
	"spin": { "definition": "thorn", "words": {} },
	"spir": { "definition": "breathe", "words": {} },
	"spondyl": { "definition": "vertebra", "words": {} },
	"squal": { "definition": "scaly, dirty, filthy", "words": {} },
	"squam": { "definition": "scale", "words": {} },
	"squarros": { "definition": "spreading at tips", "words": {} },
	"st": { "definition": "cause to stand; standing", "words": {} },
	"stagn": { "definition": "pool of standing water", "words": {} },
	"stala": { "definition": "dripping, trickling", "words": {} },
	"stann": { "definition": "tin", "words": {} },
	"stasi": { "definition": "standing, discord", "words": {} },
	"stasis": { "definition": "standing; still; stopped", "words": {} },
	"stear": { "definition": "fat, tallow", "words": {} },
	"steg": { "definition": "covering; roof", "words": {} },
	"stell": { "definition": "send", "words": {} },
	"sten": { "definition": "narrow", "words": {} },
	"stere": { "definition": "solid", "words": {} },
	"stern": { "definition": "breastbone", "words": {} },
	"stich": { "definition": "line, row", "words": {} },
	"stigmat": { "definition": "mark, puncture", "words": {} },
	"still": { "definition": "drip", "words": {} },
	"stimul": { "definition": "goad, rouse, excite", "words": {} },
	"stin": { "definition": "stand", "words": {} },
	"stoch": { "definition": "aim", "words": {} },
	"stom": { "definition": "mouth", "words": {} },
	"streper": { "definition": "noise", "words": {} },
	"strept": { "definition": "twisted", "words": {} },
	"strig": { "definition": "compress", "words": {} },
	"strigos": { "definition": "having stiff bristles", "words": {} },
	"stroph": { "definition": "turning", "words": {} },
	"stud": { "definition": "dedication", "words": {} },
	"stup": { "definition": "wonder", "words": {} },
	"styl": { "definition": "column, pillar", "words": {} },
	"suav": { "definition": "sweet", "words": {} },
	"sub": { "definition": "below", "words": {} },
	"subter": { "definition": "under", "words": {} },
	"sucr": { "definition": "sugar", "words": {} },
	"sud": { "definition": "sweat", "words": {} },
	"sui": { "definition": "self", "words": {} },
	"sulc": { "definition": "furrow", "words": {} },
	"sum": { "definition": "sum", "words": {} },
	"super": { "definition": "above, over", "words": {} },
	"supin": { "definition": "lying back", "words": {} },
	"supra": { "definition": "above, over", "words": {} },
	"surd": { "definition": "deaf", "words": {} },
	"surg": { "definition": "rise", "words": {} },
	"syn": { "definition": "together; with", "words": {} },
	"syring": { "definition": "pipe", "words": {} },
	"tach": { "definition": "swift", "words": {} },
	"taeni": { "definition": "ribbon", "words": {} },
	"tal": { "definition": "ankle", "words": {} },
	"tapet": { "definition": "carpet", "words": {} },
	"tard": { "definition": "slow", "words": {} },
	"tars": { "definition": "ankle", "words": {} },
	"taur": { "definition": "bull", "words": {} },
	"tax": { "definition": "arrangement, order", "words": {} },
	"techn": { "definition": "art, skill", "words": {} },
	"tele": { "definition": "far, end", "words": {} },
	"temn": { "definition": "cut", "words": {} },
	"tempor": { "definition": "time", "words": {} },
	"tend": { "definition": "strech; strain", "words": {} },
	"tenu": { "definition": "slender, thin", "words": {} },
	"tep": { "definition": "be warm", "words": {} },
	"teret": { "definition": "rounded", "words": {} },
	"termin": { "definition": "boundary, limit, end", "words": {} },
	"tern": { "definition": "three each", "words": {} },
	"terr": { "definition": "earth", "words": {} },
	"terti": { "definition": "third", "words": {} },
	"test": { "definition": "witness", "words": {} },
	"tetr": { "definition": "four", "words": {} },
	"thalam": { "definition": "chamber, bed", "words": {} },
	"thalass": { "definition": "sea", "words": {} },
	"than": { "definition": "death", "words": {} },
	"the": { "definition": "put", "words": {} },
	"thel": { "definition": "nipple", "words": {} },
	"theori": { "definition": "speculation", "words": {} },
	"ther": { "definition": "animal; beast", "words": {} },
	"therm": { "definition": "heat, warm", "words": {} },
	"thym": { "definition": "mood", "words": {} },
	"thyr": { "definition": "door", "words": {} },
	"thyre": { "definition": "large shield", "words": {} },
	"tim": { "definition": "most", "words": {} },
	"tim(2)": { "definition": "be afraid", "words": {} },
	"tom": { "definition": "cut; insicion", "words": {} },
	"ton": { "definition": "stretch", "words": {} },
	"top": { "definition": "place", "words": {} },
	"torpe": { "definition": "be numb", "words": {} },
	"tot": { "definition": "all, whole", "words": {} },
	"tox": { "definition": "arrow, bow", "words": {} },
	"trab": { "definition": "beam", "words": {} },
	"trachy": { "definition": "rough", "words": {} },
	"trag": { "definition": "goat", "words": {} },
	"trapez": { "definition": "four-sided, table", "words": {} },
	"traum": { "definition": "wound", "words": {} },
	"trecent": { "definition": "three hundred", "words": {} },
	"tredec": { "definition": "thirteen", "words": {} },
	"treiskaidek": { "definition": "thirteen", "words": {} },
	"trem": { "definition": "tremble", "words": {} },
	"trema": { "definition": "hole", "words": {} },
	"trepid": { "definition": "tremble", "words": {} },
	"tri": { "definition": "three", "words": {} },
	"trib": { "definition": "rub", "words": {} },
	"tribu": { "definition": "pay", "words": {} },
	"tricen": { "definition": "thirty each", "words": {} },
	"trich": { "definition": "hair", "words": {} },
	"trin": { "definition": "three each", "words": {} },
	"trit": { "definition": "third", "words": {} },
	"tritic": { "definition": "wheat", "words": {} },
	"troch": { "definition": "wheel", "words": {} },
	"trop": { "definition": "turning", "words": {} },
	"troph": { "definition": "feed, grow", "words": {} },
	"trunc": { "definition": "cut off", "words": {} },
	"tum": { "definition": "to swell up", "words": {} },
	"turb": { "definition": "disturb", "words": {} },
	"tuss": { "definition": "cough", "words": {} },
	"tympan": { "definition": "drum", "words": {} },
	"typ": { "definition": "stamp, model", "words": {} },
	"uber": { "definition": "fruitful", "words": {} },
	"uligin": { "definition": "in marshes", "words": {} },
	"ulo": { "definition": "wooly", "words": {} },
	"ultim": { "definition": "farthest", "words": {} },
	"ultra": { "definition": "beyond", "words": {} },
	"umbilic": { "definition": "navel", "words": {} },
	"umbr": { "definition": "shade, shadow", "words": {} },
	"un": { "definition": "one", "words": {} },
	"unc": { "definition": "hooked", "words": {} },
	"unci": { "definition": "ounce, twelfth", "words": {} },
	"und": { "definition": "wave", "words": {} },
	"undecim": { "definition": "eleventh", "words": {} },
	"unden": { "definition": "eleven each", "words": {} },
	"ungui": { "definition": "claw, nail", "words": {} },
	"ungul": { "definition": "claw, hoof", "words": {} },
	"ur": { "definition": "urine", "words": {} },
	"urb": { "definition": "city", "words": {} },
	"urg": { "definition": "work", "words": {} },
	"urs": { "definition": "bear", "words": {} },
	"uv": { "definition": "grape", "words": {} },
	"uxor": { "definition": "wife", "words": {} },
	"vac": { "definition": "empty", "words": {} },
	"vacc": { "definition": "cow", "words": {} },
	"vacil": { "definition": "waver", "words": {} },
	"vag": { "definition": "wander", "words": {} },
	"val": { "definition": "strength, worth", "words": {} },
	"van": { "definition": "empty, vain, idle", "words": {} },
	"vap": { "definition": "lack (of)", "words": {} },
	"vari": { "definition": "vary", "words": {} },
	"varic": { "definition": "straddle", "words": {} },
	"vel": { "definition": "veil", "words": {} },
	"veloc": { "definition": "quick", "words": {} },
	"ven": { "definition": "hunt", "words": {} },
	"vend": { "definition": "sell", "words": {} },
	"vener": { "definition": "respectful", "words": {} },
	"vent": { "definition": "wind", "words": {} },
	"ventr": { "definition": "belly", "words": {} },
	"ver": { "definition": "true", "words": {} },
	"verb": { "definition": "word", "words": {} },
	"verber": { "definition": "whip", "words": {} },
	"verm": { "definition": "worm", "words": {} },
	"vern": { "definition": "spring", "words": {} },
	"verse": { "definition": "turn", "words": {} },
	"vesic": { "definition": "bladder", "words": {} },
	"vesper": { "definition": "evening, western", "words": {} },
	"vest": { "definition": "clothing garment", "words": {} },
	"vestig": { "definition": "track", "words": {} },
	"vet": { "definition": "forbid", "words": {} },
	"veter": { "definition": "old", "words": {} },
	"vi": { "definition": "way", "words": {} },
	"vic": { "definition": "change", "words": {} },
	"vigil": { "definition": "watchful", "words": {} },
	"vil": { "definition": "cheap", "words": {} },
	"vill": { "definition": "shaggy hair", "words": {} },
	"vin": { "definition": "wine", "words": {} },
	"vir": { "definition": "green", "words": {} },
	"visc": { "definition": "thick", "words": {} },
	"viscer": { "definition": "internal organ", "words": {} },
	"vit": { "definition": "life", "words": {} },
	"vitell": { "definition": "yolk", "words": {} },
	"viti": { "definition": "fault", "words": {} },
	"vitr": { "definition": "glass", "words": {} },
	"viv": { "definition": "live", "words": {} },
	"voc": { "definition": "call, voice", "words": {} },
	"vol": { "definition": "will", "words": {} },
	"vom": { "definition": "discharge", "words": {} },
	"vulg": { "definition": "crowd", "words": {} },
	"vulner": { "definition": "wound", "words": {} },
	"vulp": { "definition": "fox", "words": {} },
	"xanth": { "definition": "yellow", "words": {} },
	"xen": { "definition": "foreign", "words": {} },
	"xer": { "definition": "dry", "words": {} },
	"xiph": { "definition": "sword", "words": {} },
	"xyl": { "definition": "wood", "words": {} },
	"ze": { "definition": "boil", "words": {} },
	"zel": { "definition": "jealousy, zeal", "words": {} },
	"zete": { "definition": "seek", "words": {} },
	"zo": { "definition": "animal; living being", "words": {} },
	"zon": { "definition": "belt, girdle", "words": {} },
	"zym": { "definition": "ferment", "words": {} },
};

var words = {
	"Mesolithic": { "rootNames": [ "mes", "lith", ], "definition": "relating to the middle part of the Stone Age", "roots": {} },
	"accurate": { "rootNames": [ "acu", ], "definition": "precise; exact", "roots": {} },
	"acrophobia": { "rootNames": [ "acr", "phob", ], "definition": "fear of heights", "roots": {} },
	"acropolis": { "rootNames": [ "acr", "poli", ], "definition": "city on a hill; fortress", "roots": {} },
	"acupuncture": { "rootNames": [ "acu", "punct", ], "definition": "insertion of needles", "roots": {} },
	"acute": { "rootNames": [ "acu", ], "definition": "sharp or severe in effect", "roots": {} },
	"aerobiosis": { "rootNames": [ "aero", "bio", ], "definition": "life in an environment with air", "roots": {} },
	"aerodynamic": { "rootNames": [ "aero", "dyna", ], "definition": "air in motion", "roots": {} },
	"aerosinusitis": { "rootNames": [ "aero", "itis", "sinus", ], "definition": "air causes inflammation to sinuses", "roots": {} },
	"aerostatic": { "rootNames": [ "aero", ], "definition": "air not changing", "roots": {} },
	"agronomy": { "rootNames": [ "ag", "nom", ], "definition": "the science of soil management and crop production", "roots": {} },
	"ambiguous": { "rootNames": [ "ag", "ambi", ], "definition": "having a double meaning", "roots": {} },
	"antagonist": { "rootNames": [ "agogue", "anti", ], "definition": "person who opposes something", "roots": {} },
	"anthropomancy": { "rootNames": [ "anthrop", "mancy", ], "definition": "human sacrifice divintation", "roots": {} },
	"anthropomorphic": { "rootNames": [ "anthrop", "morph", ], "definition": "resembling human", "roots": {} },
	"anthropophagy": { "rootNames": [ "anthrop", "phag", ], "definition": "eating humans", "roots": {} },
	"antibiotic": { "rootNames": [ "anti", "bio", ], "definition": "preventing life", "roots": {} },
	"aquamarine": { "rootNames": [ "aqua", "mar", ], "definition": "sea water", "roots": {} },
	"aquaphobia": { "rootNames": [ "aqua", "phob", ], "definition": "fear of water", "roots": {} },
	"arthritis": { "rootNames": [ "arthr", "itis", ], "definition": "joint inflammation", "roots": {} },
	"arthropod": { "rootNames": [ "arthr", "pod", ], "definition": "jointed foot", "roots": {} },
	"benevolent": { "rootNames": [ "vol", "ben", ], "definition": "well meaning and kindly", "roots": {} },
	"bicycle": { "rootNames": [ "bi", "cycl", ], "definition": "two circles", "roots": {} },
	"biocide": { "rootNames": [ "bio", "cide", ], "definition": "killing life", "roots": {} },
	"biography": { "rootNames": [ "bio", "graph", ], "definition": "writing of your life", "roots": {} },
	"biology": { "rootNames": [ "bio", "logy", ], "definition": "study of life", "roots": {} },
	"bipod": { "rootNames": [ "bi", "pod", ], "definition": "two feet", "roots": {} },
	"blennadenitis": { "rootNames": [ "blenn", "itis", ], "definition": "inflammation of mucas glands", "roots": {} },
	"blennophobia": { "rootNames": [ "blenn", "phob", ], "definition": "fear of slime", "roots": {} },
	"blennostasis": { "rootNames": [ "blenn", "stasis", ], "definition": "suppression of mucas", "roots": {} },
	"brachiosaurus": { "rootNames": [ "brachio", "saurus", ], "definition": "armed lizard", "roots": {} },
	"bronchitis": { "rootNames": [ "bronch", "itis", ], "definition": "windpipe inflammation", "roots": {} },
	"bronchotomy": { "rootNames": [ "bronch", "tom", ], "definition": "windpipe insicion", "roots": {} },
	"brontology": { "rootNames": [ "bronto", ], "definition": "study of thunder", "roots": {} },
	"brontophobia": { "rootNames": [ "bronto", "phob", ], "definition": "fear of thunder", "roots": {} },
	"brontosaurus": { "rootNames": [ "bronto", "saurus", ], "definition": "thunder lizard", "roots": {} },
	"cacophony": { "rootNames": [ "cac", "phon", ], "definition": "a harsh, discordant mixture of sounds", "roots": {} },
	"cephalomancy": { "rootNames": [ "cephal", "mancy", ], "definition": "head divination", "roots": {} },
	"cephalopod": { "rootNames": [ "cephal", "pod", ], "definition": "head foot", "roots": {} },
	"ceratosaurus": { "rootNames": [ "cerat", "saurus", ], "definition": "horned lizard", "roots": {} },
	"chiromancy": { "rootNames": [ "chir", "mancy", ], "definition": "hand divination", "roots": {} },
	"chiropter": { "rootNames": [ "chir", "pter", ], "definition": "hand wing", "roots": {} },
	"chlorophyll": { "rootNames": [ "phyll", "chlor", ], "definition": "a green pigment, present in all green plant", "roots": {} },
	"chlorosis": { "rootNames": [ "chlor", "osis", ], "definition": "having green skin", "roots": {} },
	"circumference": { "rootNames": [ "fer", "circum", ], "definition": "boundary of a circle", "roots": {} },
	"claustrophobia": { "rootNames": [ "claus", "phob", ], "definition": "fear of closed spaces", "roots": {} },
	"connect": { "rootNames": [ "con", "nex", ], "definition": "join together", "roots": {} },
	"contend": { "rootNames": [ "con", "tend", ], "definition": "with strain", "roots": {} },
	"cornucopia": { "rootNames": [ "corn", "copi", ], "definition": "a symbol of plenty", "roots": {} },
	"cosmopolitan": { "rootNames": [ "cosm", "poli", ], "definition": "at ease with different cultures", "roots": {} },
	"cryptography": { "rootNames": [ "crypt", "graph", ], "definition": "hidden writing", "roots": {} },
	"cyclops": { "rootNames": [ "cycl", "ops", ], "definition": "circular face", "roots": {} },
	"dactylology": { "rootNames": [ "dactyl", "logy", ], "definition": "study of fingers; sign language", "roots": {} },
	"decahedron": { "rootNames": [ "dec", "hedron", ], "definition": "ten face", "roots": {} },
	"decline": { "rootNames": [ "de", "clin", ], "definition": "become smaller, fewer, or less", "roots": {} },
	"demagogue": { "rootNames": [ "agogue", "dem", ], "definition": "a leader that appeals to prejudice", "roots": {} },
	"dementia": { "rootNames": [ "ment", "de", ], "definition": "persistent disorder of the mental processes", "roots": {} },
	"democracy": { "rootNames": [ "cracy", "dem", ], "definition": "government by the whole population", "roots": {} },
	"dermatology": { "rootNames": [ "derm", "logy", ], "definition": "study of skin", "roots": {} },
	"dermatosis": { "rootNames": [ "derm", "osis", ], "definition": "having any skin disease", "roots": {} },
	"derogatory": { "rootNames": [ "rog", "de", ], "definition": "showing a critical or disrespectful attitude", "roots": {} },
	"diagram": { "rootNames": [ "gramm", "dia", ], "definition": "a simplified drawing explaining something", "roots": {} },
	"dinosaur": { "rootNames": [ "dino", "saurus", ], "definition": "terrifying lizard", "roots": {} },
	"diode": { "rootNames": [ "od", "di", ], "definition": "a semiconductor device with two terminals", "roots": {} },
	"dipole": { "rootNames": [ "pol", "di", ], "definition": "a pair of equally charged poles", "roots": {} },
	"duplicity": { "rootNames": [ "plac", "du", ], "definition": "deceitfulness; double-dealing", "roots": {} },
	"dysfunction": { "rootNames": [ "dys", "funct", ], "definition": "functioning badly", "roots": {} },
	"dysmorphic": { "rootNames": [ "dys", "morph", ], "definition": "badly shaped", "roots": {} },
	"dysphonia": { "rootNames": [ "dys", "phon", ], "definition": "bad sound", "roots": {} },
	"economy": { "rootNames": [ "nom", "eco", ], "definition": "the wealth and resources of a country or region", "roots": {} },
	"ecstatic": { "rootNames": [ "st", "ec", ], "definition": "expressing overwhelming happiness", "roots": {} },
	"ectoderm": { "rootNames": [ "ecto", "der", ], "definition": "the outermost layer of cells or tissue of an embryo", "roots": {} },
	"enterobacteria": { "rootNames": [ "entero", ], "definition": "intestine bacteria", "roots": {} },
	"enterology": { "rootNames": [ "entero", "logy", ], "definition": "study of intestine", "roots": {} },
	"entomophagous": { "rootNames": [ "en", "phag", "tom", ], "definition": "eating insects", "roots": {} },
	"epidemic": { "rootNames": [ "dem", "epi", ], "definition": "widespread, infectious disease", "roots": {} },
	"ergophobia": { "rootNames": [ "phob", "erg", ], "definition": "fear of work", "roots": {} },
	"euthanasia": { "rootNames": [ "than", "eu", ], "definition": "painless killing of a patient", "roots": {} },
	"exclude": { "rootNames": [ "claus", "ex", ], "definition": "shut out", "roots": {} },
	"extend": { "rootNames": [ "ex", "tend", ], "definition": "stretchout", "roots": {} },
	"extrusion": { "rootNames": [ "ex", ], "definition": "thrust out", "roots": {} },
	"fraticide": { "rootNames": [ "cide", "frater", ], "definition": "killing brother", "roots": {} },
	"gastrectomy": { "rootNames": [ "gastr", "tom", ], "definition": "surgical stomach removal", "roots": {} },
	"gastritis": { "rootNames": [ "gastr", "itis", ], "definition": "stomach inflammation", "roots": {} },
	"gastroenterology": { "rootNames": [ "entero", "gastr", "logy", ], "definition": "stomach intestine study", "roots": {} },
	"gastropod": { "rootNames": [ "gastr", "pod", ], "definition": "stomach foot", "roots": {} },
	"genocide": { "rootNames": [ "cide", "geno", ], "definition": "killing a race", "roots": {} },
	"halitosis": { "rootNames": [ "hal", "osis", ], "definition": "state of having bad breath", "roots": {} },
	"helicograph": { "rootNames": [ "graph", "helico", ], "definition": "instument to draw spirals", "roots": {} },
	"helicopter": { "rootNames": [ "helico", "pter", ], "definition": "spiral wing", "roots": {} },
	"hexagon": { "rootNames": [ "gon", "hex", ], "definition": "six angle", "roots": {} },
	"hexahedron": { "rootNames": [ "hedron", "hex", ], "definition": "six face", "roots": {} },
	"hippodrome": { "rootNames": [ "hipp", "drom", ], "definition": "theater or other performance venue", "roots": {} },
	"hippopotamus": { "rootNames": [ "potam", "hipp", ], "definition": "large thick-skinned semiaquatic African mammal", "roots": {} },
	"homicide": { "rootNames": [ "cide", "homin", ], "definition": "human killing", "roots": {} },
	"homonym": { "rootNames": [ "onym", "hom", ], "definition": "words having the same spelling but different meanings", "roots": {} },
	"homophone": { "rootNames": [ "hom", "phon", ], "definition": "same sound", "roots": {} },
	"hydro": { "rootNames": [ "aqua", "hydrochloric", ], "definition": "water", "roots": {} },
	"hydrochloric": { "rootNames": [ "chlor", ], "definition": "green acid water", "roots": {} },
	"hypnosis": { "rootNames": [ "hypn", "osis", ], "definition": "the state of sleep", "roots": {} },
	"hypothermia": { "rootNames": [ "therm", "hyp", ], "definition": "dangerously low body temperature", "roots": {} },
	"keratosis": { "rootNames": [ "cerat", "osis", ], "definition": "having horny-like growth", "roots": {} },
	"malevolent": { "rootNames": [ "vol", "mal", ], "definition": "showing a wish to do evil", "roots": {} },
	"malodorous": { "rootNames": [ "odor", "mal", ], "definition": "smelling very unpleasant", "roots": {} },
	"medieval": { "rootNames": [ "aev", "medi", ], "definition": "relating to the Middle Ages", "roots": {} },
	"melanoma": { "rootNames": [ "oma", "melan", ], "definition": "malignant tumor associated with skin cancer", "roots": {} },
	"metamorphosis": { "rootNames": [ "meta", "morph", "osis", ], "definition": "action of changing shape", "roots": {} },
	"metropolis": { "rootNames": [ "metr", "poli", ], "definition": "capitol or chief city", "roots": {} },
	"microcosm": { "rootNames": [ "micro", "cosm", ], "definition": "a small, representative system", "roots": {} },
	"microphone": { "rootNames": [ "phon", "micro", ], "definition": "an instrument for converting sound waves into electrical energy", "roots": {} },
	"monochrome": { "rootNames": [ "chrom", "mon", ], "definition": "one color", "roots": {} },
	"monograph": { "rootNames": [ "graph", "mon", ], "definition": "one writer", "roots": {} },
	"monolith": { "rootNames": [ "mon", "lith", ], "definition": "a large single upright block of stone", "roots": {} },
	"monologue": { "rootNames": [ "logy", "mon", ], "definition": "one speaker", "roots": {} },
	"monophonic": { "rootNames": [ "mon", "phon", ], "definition": "one sound", "roots": {} },
	"monopoly": { "rootNames": [ "mon", "polien", ], "definition": "one seller", "roots": {} },
	"monotone": { "rootNames": [ "ton", "mon", ], "definition": "a sound that doesn't change pitch", "roots": {} },
	"monotreme": { "rootNames": [ "mon", "trema", ], "definition": "one hole", "roots": {} },
	"necromancy": { "rootNames": [ "mancy", "necr", ], "definition": "dead divination", "roots": {} },
	"necrophobia": { "rootNames": [ "necr", "phob", ], "definition": "fear of dead", "roots": {} },
	"necrosis": { "rootNames": [ "necr", "osis", ], "definition": "the state of death", "roots": {} },
	"necrotomy": { "rootNames": [ "necr", "tom", ], "definition": "cutting dead bodies", "roots": {} },
	"noctilucent": { "rootNames": [ "noct", "luc", ], "definition": "shining at night", "roots": {} },
	"octogon": { "rootNames": [ "gon", "oct", ], "definition": "eight angle", "roots": {} },
	"octopus": { "rootNames": [ "oct", "pod", ], "definition": "eight foot", "roots": {} },
	"omniscient": { "rootNames": [ "sci", "omni", ], "definition": "all-knowing", "roots": {} },
	"optimum": { "rootNames": [ "tim", "optim", ], "definition": "the most favorable condition", "roots": {} },
	"ornithology": { "rootNames": [ "logy", "ornith", ], "definition": "study of birds", "roots": {} },
	"ornithophobia": { "rootNames": [ "ornith", "phob", ], "definition": "fear of birds", "roots": {} },
	"orthodontist": { "rootNames": [ "orth", "odont", ], "definition": "correction of irregularities of theteeth", "roots": {} },
	"orthopedic": { "rootNames": [ "paed", "orth", ], "definition": "correction of problems in the skeleton, muscles, joints, and ligaments", "roots": {} },
	"oxymoron": { "rootNames": [ "oxy", "mor", ], "definition": "when contradictory terms are combined", "roots": {} },
	"pachycephalosaurus": { "rootNames": [ "cephal", "pach", "saurus", ], "definition": "thick headed lizard", "roots": {} },
	"pachyderm": { "rootNames": [ "derm", "pach", ], "definition": "thick skin", "roots": {} },
	"palindrome": { "rootNames": [ "palin", "drom", ], "definition": "reads the same backward or forward", "roots": {} },
	"pentagamy": { "rootNames": [ "gamy", "penta", ], "definition": "five spouses", "roots": {} },
	"pentagon": { "rootNames": [ "gon", "penta", ], "definition": "five angle", "roots": {} },
	"pentagram": { "rootNames": [ "pent", "gramm", ], "definition": "five pointed star-shaped figure", "roots": {} },
	"pentode": { "rootNames": [ "pent", "od", ], "definition": "an electronic valve having five electrodes", "roots": {} },
	"penumbra": { "rootNames": [ "umbr", "pen", ], "definition": "partial shadow between light and dark regions", "roots": {} },
	"phonograph": { "rootNames": [ "graph", "phon", ], "definition": "writing to sound", "roots": {} },
	"photograph": { "rootNames": [ "graph", "photo", ], "definition": "light drawing", "roots": {} },
	"photosythensis": { "rootNames": [ "photo", "syn", "the", ], "definition": "putting light together", "roots": {} },
	"podiatry": { "rootNames": [ "iatry", "pod", ], "definition": "foot healing", "roots": {} },
	"pogonotrophy": { "rootNames": [ "troph", "pogon", ], "definition": "beard-growing", "roots": {} },
	"polychrome": { "rootNames": [ "chrom", "poly", ], "definition": "many colors", "roots": {} },
	"polydactyl": { "rootNames": [ "dactyl", "poly", ], "definition": "many fingered", "roots": {} },
	"polygamy": { "rootNames": [ "gamy", "poly", ], "definition": "many spouses", "roots": {} },
	"polygon": { "rootNames": [ "gon", "poly", ], "definition": "many corners", "roots": {} },
	"polypod": { "rootNames": [ "pod", "poly", ], "definition": "many foot", "roots": {} },
	"primeval": { "rootNames": [ "aev", "prim", ], "definition": "earliest ages", "roots": {} },
	"privilege": { "rootNames": [ "priv", "leg", ], "definition": "a benefit granted", "roots": {} },
	"prototype": { "rootNames": [ "typ", "prot", ], "definition": "the original model", "roots": {} },
	"pseudonym": { "rootNames": [ "pseud", "onym", ], "definition": "a fictitious name", "roots": {} },
	"psychiatry": { "rootNames": [ "iatry", "psych", ], "definition": "mind healing", "roots": {} },
	"psychology": { "rootNames": [ "logy", "psych", ], "definition": "study of the mind", "roots": {} },
	"psychosis": { "rootNames": [ "osis", "psych", ], "definition": "severe mental disorder", "roots": {} },
	"pteradactyl": { "rootNames": [ "dactyl", "pter", ], "definition": "winged toes/fingers", "roots": {} },
	"pteropod": { "rootNames": [ "pod", "pter", ], "definition": "winged foot", "roots": {} },
	"rhododendron": { "rootNames": [ "rhod", "dendr", ], "definition": "a shrub with showy flowers", "roots": {} },
	"sarcophagus": { "rootNames": [ "sarc", "phag", ], "definition": "a stone coffin", "roots": {} },
	"sauropod": { "rootNames": [ "pod", "saurus", ], "definition": "lizard foot", "roots": {} },
	"scleroderma": { "rootNames": [ "scler", "der", ], "definition": "disease that hardens connective tissues", "roots": {} },
	"solstice": { "rootNames": [ "sol", "sist", ], "definition": "the two times a year when the sun is at its greatest distance from the celestial equator", "roots": {} },
	"sophomoric": { "rootNames": [ "soph", "mor", ], "definition": "intellectually pretentious", "roots": {} },
	"sororicide": { "rootNames": [ "cide", "soror", ], "definition": "killing sister", "roots": {} },
	"stasiphobia": { "rootNames": [ "phob", "stasis", ], "definition": "fear of standing", "roots": {} },
	"stasis dermatitis": { "rootNames": [ "derm", "itis", "stasis", ], "definition": "impaired circulation in legs", "roots": {} },
	"steganography": { "rootNames": [ "graph", "steg", ], "definition": "writing covering", "roots": {} },
	"stegosaurus": { "rootNames": [ "saurus", "steg", ], "definition": "covered lizard", "roots": {} },
	"submarine": { "rootNames": [ "mar", "sub", ], "definition": "below sea", "roots": {} },
	"submerge": { "rootNames": [ "merg", "sub", ], "definition": "plunge below", "roots": {} },
	"supercilious": { "rootNames": [ "super", "cili", ], "definition": "haughtily disdainful or contemptuous", "roots": {} },
	"superstition": { "rootNames": [ "super", "st", ], "definition": "a belief not based on reason or knowledge", "roots": {} },
	"survive": { "rootNames": [ "viv", "super", ], "definition": "to remain alive after the death of someone", "roots": {} },
	"telegram": { "rootNames": [ "tele", "gramm", ], "definition": "message sent over wires", "roots": {} },
	"tetrode": { "rootNames": [ "tetr", "od", ], "definition": "a vacuum tube containing four electrodes", "roots": {} },
	"theromorpha": { "rootNames": [ "morph", "ther", ], "definition": "animal shape", "roots": {} },
	"theropod": { "rootNames": [ "pod", "ther", ], "definition": "beast foot", "roots": {} },
	"therosaurus": { "rootNames": [ "saurus", "ther", ], "definition": "beast lizard", "roots": {} },
	"triceratops": { "rootNames": [ "cerat", "ops", "tri", ], "definition": "three horned face", "roots": {} },
	"trigon": { "rootNames": [ "gon", "tri", ], "definition": "three angle", "roots": {} },
	"triode": { "rootNames": [ "tri", "od", ], "definition": "a vacuum tube containing three elements", "roots": {} },
	"tripod": { "rootNames": [ "pod", "tri", ], "definition": "three foot", "roots": {} },
	"triumvirate": { "rootNames": [ "vir", "tri", ], "definition": "a government of three officers", "roots": {} },
	"tyrannosaurus rex": { "rootNames": [ "rex", "saurus", ], "definition": "tyrant lizard king", "roots": {} },
	"unicorn": { "rootNames": [ "cerat", "un", ], "definition": "one horn", "roots": {} },
	"unicycle": { "rootNames": [ "cycl", "un", ], "definition": "one circle", "roots": {} },
	"universe": { "rootNames": [ "un", "verse", ], "definition": "turned to one", "roots": {} },
	"zoology": { "rootNames": [ "logy", "zo", ], "definition": "study of animals", "roots": {} },
	"zoophobia": { "rootNames": [ "phob", "zo", ], "definition": "fear of animals", "roots": {} },
};
